### PR TITLE
fix: migrate from react-infinite-calendar to react-calendar

### LINKED ISSUE #1419: Migrate away from react-infinite-calendar
The [react-infinite-calendar](https://github.com/clauderic/react-infinite-calendar) package has been unmaintained for years and doesn't support React 18. We should migrate to a different package for our calendar UI.

It looks like the only place we use this is inside of `TransactionDateRangeFilter.tsx`. I'm sure we could find a suitable replacement

### PR DESCRIPTION
**Pull request by babyitachi**
- replacing react-infinite-calendar with react-calendar
- declaring dataTypes matching the react-calendar
- adjusting UTC and ISO time formats as per newer library 

closes #1419

### CODE REVIEW

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
It's good to see the calendar migration! This will need to be reviewed by the Cypress.io team, so you may need to wait a little while, as I know they are very busy at the moment.

From an initial review, where I didn't look at the calendar migration itself, I would ask you to please remove changes to files that are unrelated to the calendar migration. These files should not be part of the PR:

- .all-contributorsrc
- .github/workflows/add_issue_to_triage_board.yml
- .github/workflows/triage_new_comment_workflow.yml
- cypress/tsconfig.json
- eslint.config.mjs
- scripts/tsconfig.json

Cypress repos generally use single quotes, however the linting has not been modified in this repo yet to enforce this. Unfortunately this can lead to inconsistencies at the moment.

I have it on my todo list, but haven't actioned it yet, as it was dependent on the merge of https://github.com/cypress-io/cypress-realworld-app/pull/1643, which migrated linting to ESLint 9.x and took several weeks before it was reviewed by the Cypress.io team. (I also have 2 open PRs queued up waiting for review.)

**Comment by babyitachi** [comment]
> It's good to see the calendar migration! This will need to be reviewed by the Cypress.io team, so you may need to wait a little while, as I know they are very busy at the moment.
> 
> From an initial review, where I didn't look at the calendar migration itself, I would ask you to please remove changes to files that are unrelated to the calendar migration. These files should not be part of the PR:
> 
> * .all-contributorsrc
> * .github/workflows/add_issue_to_triage_board.yml
> * .github/workflows/triage_new_comment_workflow.yml
> * cypress/tsconfig.json
> * eslint.config.mjs
> * scripts/tsconfig.json
> 
> Cypress repos generally use single quotes, however the linting has not been modified in this repo yet to enforce this. Unfortunately this can lead to inconsistencies at the moment.
> 
> I have it on my todo list, but haven't actioned it yet, as it was dependent on the merge of #1643, which migrated linting to ESLint 9.x and took several weeks before it was reviewed by the Cypress.io team.

Let me remove those file from the pull request then. Sure @MikeMcC399, I'll wait for the Cypress.io team to review. Thanks!

**Comment by MikeMcC399** [comment]
@babyitachi 

Thank you very much for your work on this!

I see you removed the files you linted. That is good!

There are scripts set up for linting that don't actually lint the files that you tried to lint, so this is what you should be using in future:

```shell
yarn run lint
```

or

```shell
yarn run prettier
````

Don't run Prettier manually against all files!

I will take a look at the calendar work soon.

**Comment by MikeMcC399** [comment]
- To clarify about the linting I opened a new issue https://github.com/cypress-io/cypress-realworld-app/issues/1651

**Review by MikeMcC399 — APPROVED** [review]
LGTM!

This PR also finally allows `npm install` to work, freeing up the migration choice if / when Yarn Classic v1 is replaced as package manager (see https://github.com/cypress-io/cypress-realworld-app/issues/1423)

@babyitachi 

If you add the text `closes #1419` to your original post, then the PR will be linked to the issue.
It's also possible for a moderator to link to https://github.com/cypress-io/cypress-realworld-app/issues/1419

I don't have the authority to approve though, since I'm an external contributor, not a member of the Cypress.io team.

**Comment by MikeMcC399** [comment]
@jennifer-shehane / @AtofStryker 

This would be an important PR to review to move the repo forward.  I see that Cypress is using the repo in promotional videos, so I assume that it retains its general importance and need for regular maintenance.

- This PR resolves the two-year-old issue https://github.com/cypress-io/cypress-realworld-app/issues/1419 from @astone123 that the Cypress.io team has not addressed themselves.

I have also a couple of routine PRs in this repo queued up and waiting for review for a couple of weeks. I will highlight these again after the Cypress 15 release if they are still unreviewed at that time.

**Comment by AtofStryker** [comment]
@MikeMcC399 I will take a look at this. For your PRs, can you tag me so I can take a look?

**Comment by MikeMcC399** [comment]
@AtofStryker 

>  I will take a look at this. For your PRs, can you tag me so I can take a look?

Thank you! Unfortunately merging https://github.com/cypress-io/cypress-realworld-app/pull/1648 has caused a conflict in this PR's `yarn.lock`. Can you resolve this?

**Comment by AtofStryker** [comment]
@MikeMcC399 I'll resolve it. Works out as I need to run everything locally on the fork!

File: src/utils/transactionUtils.ts [hunk 1]
```diff
@@ -181,12 +182,89 @@ export const getPaginatedItems = (page: number, limit: number, items: any) => {
...
+    pad(date.getDate()),
+    "T",
+    pad(date.getHours()),
+    ":",
+    pad(date.getMinutes()),
+    ":",
+    pad(date.getSeconds()),
+    ms ? "." + String(ms).padStart(3, "0") : "",
+  ].join("");
+}
```
Comment (AtofStryker) [inline src/utils/transactionUtils.ts]: @babyitachi can you leverage a date utility library here to make the parsing logic simpler? We also want to make sure the dates are converted correctly as converting back and forth to/from iso is going to take your local time zone into account. The suggestion here uses `date-fns-tz` and treats the date object as if it were declared in UTC regardless of timezone. 

```suggestion
import { parseISO } from "date-fns";
import { formatInTimeZone, fromZonedTime } from "date-fns-tz";

const timezone = 'UTC'

const getDateParts = (isoString: string) => {
  const date = parseISO(isoString)
  const day = Number(formatInTimeZone(date, timezone, 'd'))
  const month = Number(formatInTimeZone(date, timezone, 'M')) - 1
  const year = Number(formatInTimeZone(date, timezone, 'Y'))
  const hour = Number(formatInTimeZone(date, timezone, 'H'))
  const minute = Number(formatInTimeZone(date, timezone, 'm'))
  const second = Number(formatInTimeZone(date, timezone, 's'))
  const ms = Number(formatInTimeZone(date, timezone, 'SSS'))
  return { day, month, year, hour, minute, second, ms }
}

export function isoStringToLocalMidnightStart(isoString: string) {
  const { year, month, day } = getDateParts(isoString)
  return new Date(year, month, day, 0, 0, 0, 0);
}

export function isoStringToLocalMidnightEnd(isoString: string) {
  const { year, month, day } = getDateParts(isoString)
  return new Date(year, month, day, 23, 59, 59, 999);
}

export function isoStringToLocalDateFull(isoString: string): Date {
  const { year, month, day, hour, minute, second, ms = 0} =  getDateParts(isoString)
  return new Date(
    year,
    month,
    day,
    hour,
    minute,
    second,
    ms
  );
}

export function localDateToIsoString(date: Date): string {
  return fromZonedTime(date, timezone).toISOString()
}
```

**Review by AtofStryker — DISMISSED** [review]
Looks great and is a good improvement. Only suggestion I have is to abstract the date parsing logic

File: src/utils/transactionUtils.ts (hunk 1 above)
Comment (AtofStryker) [reply src/utils/transactionUtils.ts]: @babyitachi I can also add this on your behalf if you are busy. Just let me know!

Comment (babyitachi) [reply src/utils/transactionUtils.ts]: @AtofStryker sure, let me try and complete it till this weekend, it might not be possible for me to do it earlier. If not done, I'll just notify you to add it on my behalf.

Thanks for reviewing!

Comment (babyitachi) [reply src/utils/transactionUtils.ts]: Hey @AtofStryker, apologies. I could not finish the above requested changes. I think if you could make a change, let's just do that and go ahead with this pull request. Thanks!

Comment (AtofStryker) [reply src/utils/transactionUtils.ts]: @babyitachi I made the changes proposed here as well as a few to the pick date range utility to simplify the code

**Comment by AtofStryker** [comment]
@jennifer-shehane I made quite a few changes to the PR. Did you want to be a second reviewer here or assign someone additionally to take a look?

File: src/utils/transactionUtils.ts (hunk 1 above)
Comment (babyitachi) [reply src/utils/transactionUtils.ts]: Thanks @AtofStryker 
Changes look good!

**Comment by jennifer-shehane** [comment]
Assigned myself. Not sure I'll get to it today though

**Review by jennifer-shehane — APPROVED** [review]
LGTM

**Comment by babyitachi** [comment]
Thanks Team. This was my First Open source. Cheers!🥂

**Comment by AtofStryker** [comment]
@babyitachi congrats! Really nice work on this!

**Comment by MikeMcC399** [comment]
Well done @babyitachi 

You made a major contribution to solving the upgrade issue which had been open for almost 2 years ! 🎉

**Comment by babyitachi** [comment]
Thanks!
Looking forward on contributing more. Please mention me whenever you need me.
