### PR TITLE
Resolve temporary wait for xstate service #334

### LINKED ISSUE #334: Awaiting XState service initialization by initialized property does not work
## Problem
We need to wait for XState services to be initialized before we can utilize them within test commands. For example, we utilize the `cy.loginByXstate()` custom command to programmatically login a user.

To await XState services, the custom command `cy.waitForXstateService` has been implemented like so:

```js
Cypress.Commands.add("waitForXstateService", (service) => {
  return cy.window({ log: false }).should((win) => {
    if (!win[service].initialized) {
      throw new Error(`${service} is not ready!`);
    }
  });
});
```

However the `initialized` property of XState services does not seem to be a reliable indicator that the service is ready for use, or the current implementation of this command is insufficient.

The undesirable and temporary fix for giving XState services to be initialized has been to introduce a 100ms wait. Disabling this small wait period causes failures across various spec files, which can be seen in this run within the Cypress Dashboard: https://dashboard.cypress.io/projects/7s5okt/runs/1180/failures

## Objective
Identify and implement a reliable indicator and method for awaiting full initialization/readiness of XState services.

### PR DESCRIPTION
**Pull request by kevinold**
Closes #334

### CODE REVIEW

File: src/machines/authMachine.ts [hunk 1]
```diff
@@ -108,18 +111,16 @@ export const authMachine = Machine<AuthMachineContext, AuthMachineSchema, AuthMa
             throw new Error("Username or password is invalid");
           });
       },
-      getUserProfile: async (ctx, event) => {
-        const resp = await httpClient.get(`http://localhost:3001/checkAuth`);
-        return resp.data;
-      },
+      getUserProfile: async (ctx, event) =>
+        await httpClient.get(`http://localhost:3001/checkAuth`).then(({ data }) => data),
```
Comment (amirrustam) [inline src/machines/authMachine.ts:115]: Any reason for chaining a `.then` instead of destructing `data` and returning similar to how you've done it in other actions?
